name: Release

on:
  push:
    tags:
      - "v*.*.*"
env:
  CARGO_TERM_COLOR: always
permissions:
  contents: write

jobs:
  publish-crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Alsa (Linux only)
        run: sudo apt-get install -yqq libasound2-dev
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Publish crate
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: soundscope
            name: soundscope-Linux-x86_64-musl.tar.gz
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: soundscope
            name: soundscope-Darwin-aarch64.tar.gz
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu
            bin: soundscope
            name: soundscope-Windows-x86_64.zip
        toolchain:
          - stable
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Alsa (Linux only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: sudo apt-get install -yqq libasound2-dev
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Run tests
        run: cargo test --verbose
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: soundscope
          target: ${{ matrix.platform.target }}
        if: matrix.toolchain == 'stable'
