name: Release Dry Run

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
permissions:
  contents: read

jobs:
  check-crate:
    name: Dry publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
      - name: Install Alsa (Linux only)
        run: sudo apt-get install -yqq libasound2-dev
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Dry-run publish
        run: cargo publish --dry-run

  build-and-test:
    name: Build & Test - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu
        toolchain:
          - stable
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Alsa (Linux only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: sudo apt-get install -yqq libasound2-dev
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Run tests
        run: cargo test --verbose
